## MCDP_CD = CS OR GS
## ORDER BY DR_NAME, DR_ID, HIRE_YMD
## 고용일자 기준 내림차순, 이름 기준 오름차순
-- 코드를 입력하세요
SELECT DR_NAME, DR_ID,MCDP_CD, DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") AS HIRE_YMD FROM DOCTOR
WHERE MCDP_CD = "CS" OR MCDP_CD = "GS"
ORDER BY HIRE_YMD desc, DR_NAME asc;