-- 코드를 입력하세요
-- TOTAL_ORDER > 3000 , INGREDIENT_TYPE = "FRUIT_BASED", ORDER BY TOTAL_ORDER DESC
SELECT F.FLAVOR FROM FIRST_HALF AS F
INNER JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR 
WHERE I.INGREDIENT_TYPE = "FRUIT_BASED" AND TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC
