-- 코드를 입력하세요
SELECT B.CATEGORY AS CATE, SUM(SALES) AS SALES FROM BOOK AS B
INNER JOIN BOOK_SALES AS S ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE LIKE "2022-01%"
GROUP BY CATE
ORDER BY CATE

# SELECT B.CATEGORY AS CATEGORY
#      , SUM(SALES) AS TOTAL_SALES
# FROM BOOK AS B
#     INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
# WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
# GROUP BY CATEGORY
# ORDER BY CATEGORY;